title: ICHEC Lecture Notes
longtitle: Lecture Notes on various topics from ICHEC team
remote_theme: sighingnow/jekyll-gitbook

#plugins:
#        - jekyll-relative-links
# markdown: GFM
syntax_highlighter_style: colorful

toc:
    enabled: true
    h_min: 1
    h_max: 3

relative_links:
        enabled: true
        collections: true
include:
        - README.md
        - about.md
        - random.md
#github:
#  is_project_page: false

#ignore_theme_config: true
# gems: [jekyll-mermaid]

## => Markdown Enhancements
##############################
## Mathjax
mathjax: # true # (default false)
mathjax_autoNumber: true # (default false)

## Mermaid
mermaid: true # (default false)

## Chart
chart: true # (default false)
