plugins:
        - jekyll-relative-links
markdown: GFM
remote_theme: sighingnow/jekyll-gitbook
syntax_highlighter_style: colorful

toc:
    enabled: true
    h_min: 1
    h_max: 3

relative_links:
        enabled: true
        collections: true
include:
        - README.md
        - about.md
        - random.md
github:
  is_project_page: false

ignore_theme_config: true
gems: [jekyll-mermaid]
